# ============================================================================
# 🌉 BACKEND API ROUTES - TRAEFIK BRIDGE
# ============================================================================
# Roteamento específico para comunicação com backend-prod via bridge network

http:
  routers:
    # Roteamento para backend-prod via bridge network
    backend-prod-public-v1:
      rule: "(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`)"
      entrypoints:
        - websecure
      middlewares:
        - security-headers-api
        - cors-api
      service: backend-service-bridge
      tls:
        certresolver: letsencrypt

    backend-prod-resultados:
      rule: "(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/resultados/publico`)"
      entrypoints:
        - websecure
      middlewares:
        - security-headers-api
        - cors-api
      service: backend-service-bridge
      tls:
        certresolver: letsencrypt

    backend-prod-horario:
      rule: "(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/horario/publico`)"
      entrypoints:
        - websecure
      middlewares:
        - security-headers-api
        - cors-api
      service: backend-service-bridge
      tls:
        certresolver: letsencrypt

    backend-prod-usuarios:
      rule: "(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/usuarios/publico`)"
      entrypoints:
        - websecure
      middlewares:
        - security-headers-api
        - cors-api
      service: backend-service-bridge
      tls:
        certresolver: letsencrypt

    backend-prod-info:
      rule: "(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/info`)"
      entrypoints:
        - websecure
      middlewares:
        - security-headers-api
        - cors-api
      service: backend-service-bridge
      tls:
        certresolver: letsencrypt

    backend-prod-rest:
      rule: "(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/rest`)"
      entrypoints:
        - websecure
      middlewares:
        - security-headers-api
        - cors-api
      service: backend-service-bridge
      tls:
        certresolver: letsencrypt

  services:
    backend-service-bridge:
      loadbalancer:
        servers:
          - url: "http://backend-prod:8080"
        passHostHeader: true
        healthCheck:
          path: /actuator/health
          interval: "60s"  # Aumentado de 30s para 60s
          timeout: "15s"   # Aumentado de 5s para 15s