# Dynamic configuration loaded via file provider
# Add routers, services, middlewares or TLS options here.

http:
  middlewares:
    example-headers:
      headers:
        customResponseHeaders:
          X-Example: "Traefik dynamic config loaded"

    backend-prod-stripprefix:
      stripPrefix:
        prefixes:
          - "/rest"

    backend-teste-stripprefix:
      stripPrefix:
        prefixes:
          - "/teste/rest"

    frontend-frete-stripprefix:
      stripPrefix:
        prefixes:
          - "/teste/frete"