# ===== DYNAMIC CONFIGURATION FOR MICROSERVICES =====
# Configuration loaded via file provider for Traefik v3.1

http:
  middlewares:
    # ===== SECURITY HEADERS =====
    security-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: "DENY"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Strict-Transport-Security: "max-age=31536000; includeSubDomains"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https: wss:"
          Permissions-Policy: "camera=(), microphone=(), geolocation=(), interest-cohort=()"
          X-Robots-Tag: "noindex, nofollow"

    # ===== CORS CONFIGURATION =====
    cors-api:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://www.conexaodesorte.com.br"
          - "https://conexaodesorte.com.br"
          - "https://api.conexaodesorte.com.br"
        accessControlMaxAge: 86400
        addVaryHeader: true
        accessControlAllowCredentials: true

    # ===== RATE LIMITING =====
    rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: "1m"
        
    rate-limit-strict:
      rateLimit:
        average: 10
        burst: 20
        period: "1m"
        
    rate-limit-notifications:
      rateLimit:
        average: 50
        burst: 100
        period: "1m"

    # ===== AUTHENTICATION =====
    admin-auth:
      basicAuth:
        usersFile: "/secrets/admin-users"
        realm: "Admin Access Required"
        
    audit-auth:
      basicAuth:
        usersFile: "/secrets/audit-users"
        realm: "Audit Access Required"
        
    crypto-auth:
      basicAuth:
        usersFile: "/secrets/crypto-users"
        realm: "Crypto Service Access Required"

    # ===== STRIP PREFIX MIDDLEWARES =====
    # Authentication service
    auth-stripprefix:
      stripPrefix:
        prefixes:
          - "/auth"
          
    auth-legacy-stripprefix:
      stripPrefix:
        prefixes:
          - "/rest/auth"

    # Results service
    results-stripprefix:
      stripPrefix:
        prefixes:
          - "/results"
          
    results-legacy-stripprefix:
      stripPrefix:
        prefixes:
          - "/rest/resultados"

    # Chat service
    chat-stripprefix:
      stripPrefix:
        prefixes:
          - "/chat"

    # Notifications service
    notifications-stripprefix:
      stripPrefix:
        prefixes:
          - "/notifications"

    # Audit service
    audit-stripprefix:
      stripPrefix:
        prefixes:
          - "/audit"

    # Monitoring service
    monitoring-stripprefix:
      stripPrefix:
        prefixes:
          - "/monitoring"

    # Scheduler service
    scheduler-stripprefix:
      stripPrefix:
        prefixes:
          - "/scheduler"

    # Crypto service
    crypto-stripprefix:
      stripPrefix:
        prefixes:
          - "/crypto"

    # ===== REDIRECTS =====
    www-redirect:
      redirectRegex:
        regex: "^https://conexaodesorte.com.br/(.*)"
        replacement: "https://www.conexaodesorte.com.br/${1}"
        permanent: true

    # ===== COMPRESSION =====
    gzip:
      compress:
        excludedContentTypes:
          - "text/event-stream"

    # ===== CACHING =====
    cache-results:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=300, s-maxage=600"
          Vary: "Accept-Encoding, Accept"

    # ===== WEBSOCKET SUPPORT =====
    websocket-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Port: "443"
        customResponseHeaders:
          X-WebSocket-Enabled: "true"

    # ===== MONITORING & METRICS =====
    metrics-headers:
      headers:
        customResponseHeaders:
          X-Service-Type: "microservice"
          X-Load-Balancer: "traefik"

# ===== TLS CONFIGURATION =====
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      maxVersion: "VersionTLS13"
      sslStrategies:
        - "tls.SniStrict"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      alpnProtocols:
        - "h2"
        - "http/1.1"

# ===== SERVICES HEALTH MONITORING =====
tcp:
  middlewares:
    tcp-headers:
      ipWhiteList:
        sourceRange:
          - "172.20.0.0/16"  # Docker network range
          - "127.0.0.1/32"   # Local access
