# ===== REGRAS DE ALERTAS - PROMETHEUS =====
# Sistema: Conexão de Sorte - Backend
# Função: Definição de alertas para monitoramento proativo
# Versão: 1.0.0
# Data: $(date +"%d/%m/%Y")

groups:
  # ===== ALERTAS CRÍTICOS =====
  - name: critical_alerts
    rules:
      # Aplicação completamente down
      - alert: ApplicationDown
        expr: up{job=~"conexao-backend.*"} == 0
        for: 1m
        labels:
          severity: critical
          service: backend
          team: devops
        annotations:
          summary: "🚨 Aplicação Conexão de Sorte está DOWN"
          description: "A aplicação {{ $labels.job }} está inacessível há mais de 1 minuto."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Application-Down"
          action: "Verificar logs do container e reiniciar se necessário"

      # Taxa de erro muito alta
      - alert: HighErrorRate
        expr: |
          (
            rate(http_server_requests_total{status=~"5.."}[5m]) /
            rate(http_server_requests_total[5m])
          ) * 100 > 5
        for: 2m
        labels:
          severity: critical
          service: backend
          team: devops
        annotations:
          summary: "🚨 Taxa de erro crítica: {{ $value | humanizePercentage }}"
          description: "Taxa de erro HTTP 5xx acima de 5% nos últimos 5 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-High-Error-Rate"
          action: "Verificar logs de aplicação e banco de dados"

      # Banco de dados inacessível
      - alert: DatabaseDown
        expr: up{job="mysql"} == 0
        for: 30s
        labels:
          severity: critical
          service: database
          team: devops
        annotations:
          summary: "🚨 Banco de dados MySQL está DOWN"
          description: "MySQL está inacessível há mais de 30 segundos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Database-Down"
          action: "Verificar container MySQL e logs de banco"

      # Uso extremo de memória
      - alert: CriticalMemoryUsage
        expr: |
          (
            jvm_memory_used_bytes{area="heap"} /
            jvm_memory_max_bytes{area="heap"}
          ) * 100 > 90
        for: 2m
        labels:
          severity: critical
          service: backend
          team: devops
        annotations:
          summary: "🚨 Uso crítico de memória: {{ $value | humanizePercentage }}"
          description: "Heap JVM acima de 90% há mais de 2 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Memory-Usage"
          action: "Verificar memory leaks e considerar restart"

      # Pool de conexões esgotado
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          (
            hikaricp_connections_active /
            hikaricp_connections_max
          ) * 100 > 95
        for: 1m
        labels:
          severity: critical
          service: database
          team: devops
        annotations:
          summary: "🚨 Pool de conexões esgotado: {{ $value | humanizePercentage }}"
          description: "Pool de conexões MySQL acima de 95% há mais de 1 minuto."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Connection-Pool"
          action: "Verificar queries lentas e conexões ativas"

  # ===== ALERTAS DE WARNING =====
  - name: warning_alerts
    rules:
      # Latência alta
      - alert: HighLatency
        expr: |
          histogram_quantile(0.95,
            rate(http_server_requests_duration_seconds_bucket[5m])
          ) > 1
        for: 5m
        labels:
          severity: warning
          service: backend
          team: devops
        annotations:
          summary: "⚠️ Latência alta: {{ $value }}s (P95)"
          description: "95% das requisições estão levando mais de 1 segundo."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-High-Latency"
          action: "Verificar performance de queries e cache"

      # Uso alto de memória
      - alert: HighMemoryUsage
        expr: |
          (
            jvm_memory_used_bytes{area="heap"} /
            jvm_memory_max_bytes{area="heap"}
          ) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: backend
          team: devops
        annotations:
          summary: "⚠️ Uso alto de memória: {{ $value | humanizePercentage }}"
          description: "Heap JVM acima de 80% há mais de 5 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Memory-Usage"
          action: "Monitorar crescimento e preparar para possível restart"

      # Pool de conexões alto
      - alert: HighDatabaseConnections
        expr: |
          (
            hikaricp_connections_active /
            hikaricp_connections_max
          ) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: database
          team: devops
        annotations:
          summary: "⚠️ Uso alto do pool de conexões: {{ $value | humanizePercentage }}"
          description: "Pool de conexões MySQL acima de 80% há mais de 5 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Connection-Pool"
          action: "Monitorar queries ativas e otimizar se necessário"

      # Garbage Collection frequente
      - alert: FrequentGarbageCollection
        expr: rate(jvm_gc_collection_seconds_count[5m]) > 0.2
        for: 5m
        labels:
          severity: warning
          service: backend
          team: devops
        annotations:
          summary: "⚠️ Garbage Collection frequente: {{ $value }}/s"
          description: "GC executando mais de 0.2 vezes por segundo."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-GC-Performance"
          action: "Verificar configurações de heap e memory leaks"

      # Taxa de erro moderada
      - alert: ModerateErrorRate
        expr: |
          (
            rate(http_server_requests_total{status=~"5.."}[5m]) /
            rate(http_server_requests_total[5m])
          ) * 100 > 1
        for: 5m
        labels:
          severity: warning
          service: backend
          team: devops
        annotations:
          summary: "⚠️ Taxa de erro moderada: {{ $value | humanizePercentage }}"
          description: "Taxa de erro HTTP 5xx acima de 1% nos últimos 5 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Error-Rate"
          action: "Investigar logs para identificar causa dos erros"

  # ===== ALERTAS DE INFRAESTRUTURA =====
  - name: infrastructure_alerts
    rules:
      # Espaço em disco baixo
      - alert: LowDiskSpace
        expr: |
          (
            node_filesystem_avail_bytes{mountpoint="/"} /
            node_filesystem_size_bytes{mountpoint="/"}
          ) * 100 < 20
        for: 5m
        labels:
          severity: warning
          service: infrastructure
          team: devops
        annotations:
          summary: "⚠️ Espaço em disco baixo: {{ $value | humanizePercentage }} disponível"
          description: "Menos de 20% de espaço disponível no disco raiz."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Disk-Space"
          action: "Limpar logs antigos e verificar crescimento de dados"

      # CPU alta
      - alert: HighCPUUsage
        expr: |
          (
            100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
          ) > 80
        for: 10m
        labels:
          severity: warning
          service: infrastructure
          team: devops
        annotations:
          summary: "⚠️ Uso alto de CPU: {{ $value | humanizePercentage }}"
          description: "CPU acima de 80% há mais de 10 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-CPU-Usage"
          action: "Verificar processos consumindo CPU e otimizar"

      # Container reiniciando
      - alert: ContainerRestarting
        expr: rate(container_start_time_seconds[5m]) > 0
        for: 1m
        labels:
          severity: warning
          service: infrastructure
          team: devops
        annotations:
          summary: "⚠️ Container reiniciando: {{ $labels.name }}"
          description: "Container {{ $labels.name }} reiniciou nos últimos 5 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Container-Restart"
          action: "Verificar logs do container para identificar causa"

  # ===== ALERTAS DE NEGÓCIO =====
  - name: business_alerts
    rules:
      # Baixo volume de transações
      - alert: LowTransactionVolume
        expr: rate(http_server_requests_total{uri=~"/rest/.*"}[1h]) < 0.1
        for: 30m
        labels:
          severity: warning
          service: business
          team: product
        annotations:
          summary: "⚠️ Volume baixo de transações: {{ $value }}/s"
          description: "Menos de 0.1 transações por segundo na última hora."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Transaction-Volume"
          action: "Verificar se há problemas de conectividade ou campanhas"

      # Falhas de autenticação
      - alert: HighAuthenticationFailures
        expr: |
          rate(http_server_requests_total{status="401"}[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
          service: security
          team: security
        annotations:
          summary: "⚠️ Falhas de autenticação altas: {{ $value }}/s"
          description: "Mais de 0.5 falhas de autenticação por segundo."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Auth-Failures"
          action: "Verificar tentativas de acesso não autorizado"

  # ===== ALERTAS DE COMPLIANCE LGPD =====
  - name: lgpd_compliance_alerts
    rules:
      # Falhas no processamento de dados pessoais
      - alert: PersonalDataProcessingFailure
        expr: |
          rate(http_server_requests_total{uri=~"/rest/privacidade/.*",status=~"5.."}[5m]) > 0
        for: 1m
        labels:
          severity: critical
          service: lgpd
          team: compliance
        annotations:
          summary: "🚨 Falha no processamento de dados pessoais"
          description: "Erros nos endpoints de privacidade/LGPD detectados."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-LGPD-Compliance"
          action: "Verificar logs de privacidade e notificar DPO"

      # Volume alto de solicitações de exclusão
      - alert: HighDataDeletionRequests
        expr: |
          rate(http_server_requests_total{uri=~"/rest/privacidade/exclusao.*"}[1h]) > 10
        for: 5m
        labels:
          severity: warning
          service: lgpd
          team: compliance
        annotations:
          summary: "⚠️ Volume alto de solicitações de exclusão: {{ $value }}/h"
          description: "Mais de 10 solicitações de exclusão por hora."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Data-Deletion"
          action: "Verificar padrão de solicitações e notificar DPO"

  # ===== ALERTAS DE MONITORAMENTO =====
  - name: monitoring_alerts
    rules:
      # Prometheus perdendo dados
      - alert: PrometheusDataLoss
        expr: increase(prometheus_tsdb_symbol_table_size_bytes[1h]) < 0
        for: 5m
        labels:
          severity: warning
          service: monitoring
          team: devops
        annotations:
          summary: "⚠️ Prometheus pode estar perdendo dados"
          description: "Possível perda de dados no Prometheus detectada."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Prometheus-Data-Loss"
          action: "Verificar configuração e espaço em disco do Prometheus"

      # Grafana inacessível
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 2m
        labels:
          severity: warning
          service: monitoring
          team: devops
        annotations:
          summary: "⚠️ Grafana está inacessível"
          description: "Grafana está down há mais de 2 minutos."
          runbook_url: "https://github.com/facilita-servicos/conexao-de-sorte-backend/wiki/Runbook-Grafana-Down"
          action: "Verificar container Grafana e dependências"

# ===== CONFIGURAÇÕES GLOBAIS =====
# 
# Severidades:
# - critical: Requer ação imediata (SLA impactado)
# - warning: Requer atenção (possível impacto futuro)
# - info: Informativo (sem ação necessária)
# 
# Teams:
# - devops: Infraestrutura e operações
# - product: Produto e negócio
# - security: Segurança e compliance
# - compliance: LGPD e regulamentações
# 
# Services:
# - backend: Aplicação Spring Boot
# - database: MySQL
# - infrastructure: Sistema operacional
# - monitoring: Prometheus/Grafana
# - business: Métricas de negócio
# - lgpd: Compliance LGPD
# - security: Segurança
# 
# Runbooks:
# - Cada alerta deve ter um runbook com procedimentos
# - Links para wiki com passos de resolução
# - Comandos específicos para diagnóstico
# - Escalação em caso de falha na resolução