# =============================================================================
# 🛡️ CONEXÃO DE SORTE - SECURITY HEADERS E MIDDLEWARES MODERNOS
# =============================================================================
# Headers de segurança baseados em:
# - OWASP Security Headers
# - Mozilla Security Guidelines
# - CSP Level 3
# - Otimizado para Traefik v3.5.2
# =============================================================================

---
http:
  middlewares:
    # ==========================================================================
    # 🔐 HEADERS DE SEGURANÇA MODERNOS - OWASP COMPLIANCE
    # ==========================================================================
    security-headers:
      headers:
        # Strict Transport Security - HSTS
        customResponseHeaders:
          # HSTS avançado com preload
          Strict-Transport-Security: >-
            max-age=63072000; includeSubDomains; preload

          # Content Security Policy - CSP Level 3
          Content-Security-Policy: >-
            default-src 'self';
            script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com;
            style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com https://fonts.googleapis.com;
            font-src 'self' https://fonts.gstatic.com data:;
            img-src 'self' data: https: blob:;
            connect-src 'self' wss: ws: https:;
            media-src 'self' https: data:;
            object-src 'none';
            child-src 'self';
            frame-ancestors 'none';
            form-action 'self';
            base-uri 'self';
            manifest-src 'self';
            worker-src 'self' blob:;
            upgrade-insecure-requests;

          # Permissions Policy (sucessor do Feature Policy)
          Permissions-Policy: >-
            geolocation=(),
            camera=(),
            microphone=(),
            payment=(),
            usb=(),
            magnetometer=(),
            accelerometer=(),
            gyroscope=(),
            fullscreen=(self),
            display-capture=()

          # Headers adicionais OWASP
          X-Frame-Options: "DENY"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Cross-Origin-Opener-Policy: "same-origin"
          Cross-Origin-Embedder-Policy: "require-corp"
          Cross-Origin-Resource-Policy: "same-origin"

          # Headers customizados da aplicação
          X-Powered-By: "Conexão de Sorte API"
          X-API-Version: "v1.0.0"
          Server: ""  # Remove header Server por segurança

        # Headers de segurança básicos (compatibilidade)
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true

    # ==========================================================================
    # 🚀 HEADERS ESPECÍFICOS PARA APIs REST - PERFORMANCE + SEGURANÇA
    # ==========================================================================
    api-security-headers:
      headers:
        customResponseHeaders:
          # CSP específico para APIs (mais restritivo)
          Content-Security-Policy: >-
            default-src 'none';
            connect-src 'self';
            frame-ancestors 'none';

          # Headers específicos para APIs
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"
          X-API-Rate-Limit: "1000/hour"
          Cache-Control: "no-cache, no-store, must-revalidate"
          Pragma: "no-cache"
          Expires: "0"

          # CORS configurado dinamicamente
          Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
          Access-Control-Allow-Headers: "Authorization, Content-Type, Accept, X-Requested-With, X-API-Key"
          Access-Control-Max-Age: "86400"

        # Configurações básicas
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

    # ==========================================================================
    # 🎯 HEADERS PARA FRONTEND - OTIMIZADO PARA SPA REACT
    # ==========================================================================
    frontend-security-headers:
      headers:
        customResponseHeaders:
          # CSP otimizado para React SPA
          Content-Security-Policy: >-
            default-src 'self';
            script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net;
            style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
            font-src 'self' https://fonts.gstatic.com data:;
            img-src 'self' data: https: blob:;
            connect-src 'self' wss: https:;
            frame-ancestors 'none';
            base-uri 'self';
            form-action 'self';

          # Headers otimizados para PWA
          X-Frame-Options: "SAMEORIGIN"  # Permite embeds do próprio domínio
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "strict-origin-when-cross-origin"

          # Service Worker e PWA
          Service-Worker-Allowed: "/"

        # Configurações básicas
        frameDeny: false  # Permitir para PWA
        contentTypeNosniff: true
        browserXssFilter: true
        stsSeconds: 31536000  # 1 ano para frontend
        stsIncludeSubdomains: true

    # ==========================================================================
    # 🌐 CORS MODERNO - CONFIGURAÇÃO FLEXÍVEL E SEGURA
    # ==========================================================================
    cors-modern:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowMethods:
          - "GET"
          - "HEAD"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
          - "PATCH"
        accessControlAllowOriginList:
          - "https://conexaodesorte.com.br"
          - "https://www.conexaodesorte.com.br"
        accessControlAllowHeaders:
          - "Accept"
          - "Authorization"
          - "Content-Type"
          - "X-Requested-With"
          - "X-API-Key"
          - "X-Request-ID"
          - "X-Correlation-ID"
          - "Cache-Control"
          - "Pragma"
        accessControlExposeHeaders:
          - "X-Total-Count"
          - "X-Rate-Limit-Remaining"
          - "X-Rate-Limit-Reset"
          - "X-Request-ID"
        accessControlMaxAge: 86400
        addVaryHeader: true

    # ==========================================================================
    # 🔐 RATE LIMITING GLOBAL - PROTEÇÃO DDOS
    # ==========================================================================
    rate-limit-global:
      rateLimit:
        average: 200    # 200 requests per minute
        period: "1m"
        burst: 300      # Burst de até 300 requests
        sourceCriterion:
          ipStrategy:
            depth: 1
            excludedIPs:
              - "127.0.0.1"
              - "::1"
              - "10.0.0.0/8"
              - "172.16.0.0/12"
              - "192.168.0.0/16"

    # Rate limiting para APIs REST
    rate-limit-api:
      rateLimit:
        average: 100    # 100 requests per minute para APIs
        period: "1m"
        burst: 150
        sourceCriterion:
          ipStrategy:
            depth: 1

    # Rate limiting para autenticação (mais restritivo)
    rate-limit-auth:
      rateLimit:
        average: 10     # 10 requests per minute para login
        period: "1m"
        burst: 15
        sourceCriterion:
          ipStrategy:
            depth: 1

    # ==========================================================================
    # 🔄 REDIRECTS SEGUROS E OTIMIZADOS
    # ==========================================================================
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
        port: "443"

    redirect-to-www:
      redirectRegex:
        regex: "^https://conexaodesorte\\.com\\.br/(.*)"
        replacement: "https://www.conexaodesorte.com.br/${1}"
        permanent: true

    # ==========================================================================
    # 📦 COMPRESSÃO MODERNA - GZIP + BROTLI
    # ==========================================================================
    compression-modern:
      compress:
        minResponseBodyBytes: 1024  # Comprimir apenas responses > 1KB

    # ==========================================================================
    # 🔧 CIRCUIT BREAKER - PROTEÇÃO CONTRA FALHAS EM CASCATA
    # ==========================================================================
    circuit-breaker-api:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.30 || ResponseCodeRatio(500, 600, 0, 600) > 0.25"
        checkPeriod: "10s"
        fallbackDuration: "30s"
        recoveryDuration: "20s"

    # ==========================================================================
    # 🔁 RETRY POLICY - RESILIÊNCIA AUTOMÁTICA
    # ==========================================================================
    retry-policy:
      retry:
        attempts: 3
        initialInterval: "100ms"

    # ==========================================================================
    # 📦 STRIP PREFIX MIDDLEWARES - APIs REST v1
    # ==========================================================================
    api-strip-prefix-gateway:
      stripPrefix:
        prefixes:
          - "/api/v1/gateway"

    api-strip-prefix-auth:
      stripPrefix:
        prefixes:
          - "/api/v1/auth"

    api-strip-prefix-users:
      stripPrefix:
        prefixes:
          - "/api/v1/users"

    api-strip-prefix-results:
      stripPrefix:
        prefixes:
          - "/api/v1/results"

    api-strip-prefix-chat:
      stripPrefix:
        prefixes:
          - "/api/v1/chat"

    api-strip-prefix-chatbot:
      stripPrefix:
        prefixes:
          - "/api/v1/chatbot"

    api-strip-prefix-financial:
      stripPrefix:
        prefixes:
          - "/api/v1/financial"

    api-strip-prefix-notifications:
      stripPrefix:
        prefixes:
          - "/api/v1/notifications"

    api-strip-prefix-scheduler:
      stripPrefix:
        prefixes:
          - "/api/v1/scheduler"

    api-strip-prefix-observability:
      stripPrefix:
        prefixes:
          - "/api/v1/observability"

    api-strip-prefix-crypto:
      stripPrefix:
        prefixes:
          - "/api/v1/crypto"

    api-strip-prefix-audit:
      stripPrefix:
        prefixes:
          - "/api/v1/audit"

    # ==========================================================================
    # 📊 MIDDLEWARES ESPECÍFICOS POR FUNCIONALIDADE
    # ==========================================================================
    # Cache para resultados
    cache-results:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=300, s-maxage=300"
          ETag: "auto"
          Vary: "Accept-Encoding, Authorization"

    # Headers específicos para WebSocket (chat)
    websocket-headers:
      headers:
        customRequestHeaders:
          Connection: "upgrade"
          Upgrade: "websocket"
        customResponseHeaders:
          X-WebSocket-Support: "enabled"

    # Rate limiting para notificações
    rate-limit-notifications:
      rateLimit:
        average: 50     # 50 notificações por minuto
        period: "1m"
        burst: 75
        sourceCriterion:
          ipStrategy:
            depth: 1

    # Headers TLS moderno
    modern-tls:
      headers:
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
          X-TLS-Version: "1.3"

# =============================================================================
# 📋 CONFIGURAÇÃO DE USO DOS MIDDLEWARES
# =============================================================================
# Para usar estes middlewares nas rotas:
#
# Frontend SPA (React):
#   middlewares:
#     - frontend-security-headers@file
#     - cors-modern@file
#     - compression-modern@file
#     - rate-limit-global@file
#
# APIs REST:
#   middlewares:
#     - api-security-headers@file
#     - cors-modern@file
#     - rate-limit-api@file
#     - circuit-breaker-api@file
#     - retry-policy@file
#     - api-strip-prefix-{NOME}@file
#
# Exemplo para nova API v2:
#   - Criar novo router com /api/v2/nome
#   - Adicionar api-strip-prefix-nome-v2 middleware
#   - Configurar serviço correspondente
# =============================================================================
