---
# ============================================================================
# 🌐 BACKEND API ROUTES - CONFIGURAÇÃO LIMPA
# ============================================================================
# Este arquivo é mantido vazio propositalmente.
# Todas as rotas de API estão definidas em api-routes-modern.yml
# ============================================================================

# Arquivo vazio - sem placeholders ou serviços temporários
