# ============================================================================
# 🌐 BACKEND API PUBLIC ENDPOINTS - SWARM ONLY
# ============================================================================
# Roteamento para serviços Swarm apenas
# Backend-prod agora é gerenciado pelo Traefik Bridge

# NOTA: Este arquivo agora gerencia apenas serviços Swarm
# O backend-prod é roteado pelo Traefik Bridge (docker-compose.bridge.yml)

http:
  routers:
    # Placeholder para futuros serviços Swarm
    # backend-prod foi movido para Traefik Bridge
    
    # Exemplo de roteamento para serviços Swarm futuros:
    # backend-swarm-service:
    #   rule: "Host(`api.conexaodesorte.com.br`) && PathPrefix(`/api/v2`)"
    #   entrypoints:
    #     - websecure
    #   service: backend-swarm-service
    #   tls:
    #     certresolver: letsencrypt

  services:
    # Placeholder para futuros serviços Swarm
    # backend-service foi movido para Traefik Bridge
    
    # Exemplo de serviço Swarm futuro:
    # backend-swarm-service:
    #   loadbalancer:
    #     servers:
    #       - url: "http://backend-swarm:8080"