---
# ============================================================================
# 🌐 BACKEND API ROUTES - DOCKER SWARM ONLY
# ============================================================================
# Configurações de roteamento para serviços gerenciados por Docker Swarm
# Todas as configurações legacy do backend-prod foram removidas
# ============================================================================

http:
  routers:
    # Placeholder para futuros serviços Swarm
    # Exemplo de roteamento para serviços Swarm:
    # backend-swarm-service:
    #   rule: "Host(`api.conexaodesorte.com.br`) && PathPrefix(`/api/v2`)"
    #   entrypoints:
    #     - websecure
    #   service: backend-swarm-service
    #   tls:
    #     certresolver: letsencrypt

  services:
    # Placeholder para futuros serviços Swarm
    # Exemplo de serviço Swarm futuro:
    # backend-swarm-service:
    #   loadbalancer:
    #     servers:
    #       - url: "http://backend-swarm:8080"

    # YAML válido requer pelo menos um item, mesmo que comentado
    placeholder-service:
      loadbalancer:
        servers:
          - url: "http://placeholder:3000"
