---
# =============================================================================
# 🌐 TRAEFIK MINIMAL ROUTING CONFIGURATION - TESTE
# =============================================================================
# Configuração mínima apenas para testar se o Traefik inicializa corretamente
# Remove dependências de serviços externos para diagnóstico
# =============================================================================

http:
  routers:
    # ====================================================================
# 📊 APENAS PING/HEALTH - CONFIGURAÇÃO MÍNIMA
# ==========================================================================
# Remover todos os routers que dependem de serviços externos
# Apenas manter configurações internas do Traefik

  services:
# ==========================================================================
# 📊 SERVIÇOS INTERNOS APENAS
# ==========================================================================
# Remover todos os services que dependem de containers externos
# Apenas API interna do Traefik será usada

# =============================================================================
# Esta configuração mínima deve permitir que o Traefik inicie sem erros
# =============================================================================
