http:
  middlewares:
    gzip-compress:
      compress: {}
    
    ip-allow-local:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
    
    cors-api:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        accessControlAllowOriginList:
          - https://conexaodesorte.com.br
          - https://www.conexaodesorte.com.br
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        accessControlMaxAge: 86400
        addVaryHeader: true
    
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    
    redirect-www-to-non-www:
      redirectRegex:
        regex: '^https://www\.conexaodesorte\.com\.br/(.*)'
        replacement: 'https://conexaodesorte.com.br/${1}'
        permanent: true
    
    redirect-non-www-to-www:
      redirectRegex:
        regex: '^https://conexaodesorte\.com\.br/(.*)'
        replacement: 'https://www.conexaodesorte.com.br/${1}'
        permanent: true
    
    # Rate Limiting - Proteção contra ataques DDoS
    rate-limit-general:
      rateLimit:
        average: 100
        period: 1m
        burst: 200
    
    rate-limit-api:
      rateLimit:
        average: 50
        period: 1m
        burst: 100
    
    rate-limit-strict:
      rateLimit:
        average: 20
        period: 1m
        burst: 40
    
    # Proteção contra ataques de força bruta
    rate-limit-auth:
      rateLimit:
        average: 5
        period: 1m
        burst: 10
    
    # Circuit Breaker - Proteção contra sobrecarga
    circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.30"
        checkPeriod: 10s
        fallbackDuration: 30s
        recoveryDuration: 10s
    
    # Retry - Tentativas automáticas em caso de falha
    retry-policy:
      retry:
        attempts: 3
        initialInterval: 100ms