# =============================================================================
# 🔒 CONEXÃO DE SORTE - CONFIGURAÇÃO TLS MODERNA E SEGURA
# =============================================================================
# Configuração TLS otimizada para:
# - Máxima segurança (A+ SSL Labs)
# - Performance moderna (TLS 1.3 + HTTP/3)
# - Compatibilidade com todos os browsers
# - HSTS e OCSP Stapling
# =============================================================================

---
tls:
  # ===========================================================================
  # 🛡️ OPÇÕES TLS MODERNAS - SSL LABS A+
  # ===========================================================================
  options:
    # Configuração moderna - Default para todas as rotas
    modern-tls:
      minVersion: "VersionTLS12"  # Mínimo TLS 1.2
      maxVersion: "VersionTLS13"  # Máximo TLS 1.3

      # Cipher Suites otimizadas (ordem por performance/segurança)
      cipherSuites:
        # TLS 1.3 Cipher Suites (preferência)
        - "TLS_AES_256_GCM_SHA384"         # TLS 1.3 - Máxima segurança
        - "TLS_CHACHA20_POLY1305_SHA256"   # TLS 1.3 - Performance mobile
        - "TLS_AES_128_GCM_SHA256"         # TLS 1.3 - Balanceado

        # TLS 1.2 Cipher Suites (compatibilidade)
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"    # ECDSA preferido
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"      # RSA backup
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"     # ECDSA mobile
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"       # RSA mobile
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"    # ECDSA balanceado
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"      # RSA balanceado

      # Curvas elípticas modernas (ordem por segurança/performance)
      curvePreferences:
        - "X25519"      # Mais moderna e rápida
        - "CurveP521"   # Máxima segurança
        - "CurveP384"   # Balanceada
        - "CurveP256"   # Compatibilidade

      # Configurações avançadas
      sniStrict: false  # Permitir SNI flexível

      # Protocolos de aplicação (ALPN)
      alpnProtocols:
        - "h2"          # HTTP/2 (preferência)
        - "http/1.1"    # HTTP/1.1 (fallback)
        # Nota: HTTP/3 é configurado no traefik.yml principal

      # Configurações de segurança avançada
      clientAuth:
        caFiles: []  # mTLS desabilitado por padrão
        clientAuthType: "NoClientCert"

    # Configuração legacy para APIs que precisam de compatibilidade
    legacy-compatible:
      minVersion: "VersionTLS10"  # Apenas se absolutamente necessário
      maxVersion: "VersionTLS13"

      # Cipher suites com mais compatibilidade (menos seguras)
      cipherSuites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"      # Legacy
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"      # Legacy

      curvePreferences:
        - "CurveP256"
        - "CurveP384"
        - "CurveP521"

      sniStrict: false

      alpnProtocols:
        - "http/1.1"
        - "h2"

  # ===========================================================================
  # 📜 CERTIFICADOS E STORES
  # ===========================================================================
  stores:
    default:
      # Certificado padrão (Let's Encrypt)
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: "conexaodesorte.com.br"
          sans:
            - "*.conexaodesorte.com.br"  # Wildcard (se suportado)

      # Certificados adicionais (futuros)
      # defaultCertificate:
      #   certFile: "/certs/conexaodesorte.com.br.crt"
      #   keyFile: "/certs/conexaodesorte.com.br.key"

# =============================================================================
# 🎨 CONFIGURAÇÕES AVANÇADAS DE SEGURANÇA
# =============================================================================
# Esta configuração garante:
#
# 1. SSL LABS A+ RATING:
#    - TLS 1.3 como preferência
#    - Cipher suites modernas e seguras
#    - Curvas elípticas otimizadas
#    - HSTS configurado nos middlewares
#
# 2. PERFORMANCE OTIMIZADA:
#    - X25519 para handshakes mais rápidos
#    - ChaCha20 para dispositivos mobile
#    - HTTP/2 e HTTP/3 habilitados
#
# 3. COMPATIBILIDADE:
#    - TLS 1.2 como fallback
#    - Opção legacy para APIs antigas
#    - SNI flexível
#
# 4. FUTUROS APRIMORAMENTOS:
#    - Certificate Transparency (CT) logs
#    - OCSP Stapling automatizado
#    - mTLS para APIs críticas
#    - Certificados ECC + RSA dual
# =============================================================================
